baseURL = "https://www.josecarlos.me/"
languageCode = "es"
title = "Home | José Carlos"
theme="josecarlos.me"

[params]
helloWorldTitle="Hello, world!"
iamTitle="I'm José Carlos"
linkedin="https://www.linkedin.com/in/jose-carlos-garcia-ortega-723902a7/"
twitter="https://twitter.com/josegarciaor"
github="https://github.com/JoseCarlosGarcia95"
email="contact@josecarlos.me"
twitteruser="josegarciaor"
description="José Carlos García's personal website"
prod="true"